-- Vor dem Ausführen REPLACE_WITH_SHA256 durch den SHA-256-Hash des Familiencodes ersetzen.
with family as (
  insert into public.families(name,code_hash) values('Kanada 2026','REPLACE_WITH_SHA256') returning id
), trip as (
  insert into public.trips(family_id,name,start_date,end_date,created_by)
  select id,'Kanada 2026','2026-07-21','2026-08-11','System' from family returning id,family_id
), seed(owner,category,label,position) as (values
('Allgemein','Dokumente & Geld','Reisepässe für alle',10),
('Allgemein','Dokumente & Geld','eTA-Bestätigungen',20),
('Allgemein','Dokumente & Geld','Flug-, Hotel- und Camperunterlagen',30),
('Allgemein','Dokumente & Geld','Führerausweise und Kreditkarten',40),
('Allgemein','Dokumente & Geld','Reiseversicherung / Notfallnummern',50),
('Allgemein','Unterwegs','Kanada-Steckdosenadapter',60),
('Allgemein','Unterwegs','Powerbanks und Ladekabel',70),
('Allgemein','Unterwegs','Kopfhörer und Unterhaltung',80),
('Allgemein','Camper & Camping','Taschenlampen / Stirnlampen',90),
('Allgemein','Camper & Camping','Trinkflaschen',100),
('Allgemein','Camper & Camping','Wäscheleine und Waschmittel',110),
('Allgemein','Gesundheit','Reiseapotheke und Fiebermesser',120),
('Allgemein','Gesundheit','Sonnencreme und Mückenschutz',130),
('Allgemein','Gesundheit','Pflaster und Desinfektion',140),
('Allgemein','Freizeit','Badesachen / Badetücher',150),
('Allgemein','Freizeit','Tagesrucksäcke',160),
('Allgemein','Freizeit','Fernglas / Kamera',170),
('Marc','Kleidung','Unterwäsche und Socken',200),
('Marc','Kleidung','T-Shirts und lange Oberteile',210),
('Marc','Kleidung','Kurze und lange Hosen',220),
('Marc','Kleidung','Fleece / warmer Pullover',230),
('Marc','Kleidung','Regenjacke',240),
('Marc','Schuhe & Zubehör','Bequeme Schuhe',250),
('Marc','Schuhe & Zubehör','Sandalen / Badeschuhe',260),
('Marc','Persönlich','Toilettenartikel',270),
('Marc','Persönlich','Medikamente',280),
('Marc','Technik','Handy, Uhr und Ladegeräte',290),
('Nici','Kleidung','Unterwäsche und Socken',300),
('Nici','Kleidung','T-Shirts und lange Oberteile',310),
('Nici','Kleidung','Kurze und lange Hosen',320),
('Nici','Kleidung','Fleece / warmer Pullover',330),
('Nici','Kleidung','Regenjacke',340),
('Nici','Schuhe & Zubehör','Bequeme Schuhe',350),
('Nici','Schuhe & Zubehör','Sandalen / Badeschuhe',360),
('Nici','Persönlich','Toilettenartikel',370),
('Nici','Persönlich','Medikamente',380),
('Nici','Technik','Handy, Uhr und Ladegeräte',390),
('Nils','Kleidung','Unterwäsche und Socken',400),
('Nils','Kleidung','T-Shirts und lange Oberteile',410),
('Nils','Kleidung','Kurze und lange Hosen',420),
('Nils','Kleidung','Fleece / warmer Pullover',430),
('Nils','Kleidung','Regenjacke',440),
('Nils','Schuhe & Zubehör','Turnschuhe und Sandalen',450),
('Nils','Freizeit','Badesachen',460),
('Nils','Freizeit','Buch / Spiele / Kopfhörer',470),
('Nils','Persönlich','Zahnbürste und Toilettenartikel',480),
('Lou','Kleidung','Unterwäsche und Socken',500),
('Lou','Kleidung','T-Shirts und lange Oberteile',510),
('Lou','Kleidung','Kurze und lange Hosen',520),
('Lou','Kleidung','Fleece / warmer Pullover',530),
('Lou','Kleidung','Regenjacke',540),
('Lou','Schuhe & Zubehör','Turnschuhe und Sandalen',550),
('Lou','Freizeit','Badesachen',560),
('Lou','Freizeit','Buch / Spiele / Kopfhörer',570),
('Lou','Persönlich','Zahnbürste und Toilettenartikel',580),
('Laila','Kleidung','Bodys, Shirts und Hosen',600),
('Laila','Kleidung','Pyjamas und Schlafsack',610),
('Laila','Kleidung','Socken, Mütze und Sonnenhut',620),
('Laila','Kleidung','Warme Schicht und Regenkleidung',630),
('Laila','Pflege','Windeln und Feuchttücher für den Start',640),
('Laila','Pflege','Wickelunterlage und Wundschutz',650),
('Laila','Essen & Trinken','Fläschchen / Trinkbecher',660),
('Laila','Essen & Trinken','Lätzchen und Snacks',670),
('Laila','Schlafen & Unterwegs','Kinderwagen / Trage',680),
('Laila','Schlafen & Unterwegs','Autositz prüfen',690),
('Laila','Schlafen & Unterwegs','Lieblingskuscheltier / Schnuller',700),
('Laila','Gesundheit','Kinder-Medikamente und Dosierhilfe',710)
)
insert into public.packing_items(family_id,trip_id,owner,category,label,position,created_by)
select trip.family_id,trip.id,seed.owner,seed.category,seed.label,seed.position,'System' from trip cross join seed;

delete from public.packing_events where actor='System';
